### ISSUE TITLE
What license is attached to this module?

### ISSUE THREAD

**Issue by fgimian** [mtneug/ansible-modules-plist#1]
Hey there, really great job on this Ansible module, it's exactly what I've been looking for :smile: 

I'm interested in updating it and incorporating it into my [macbuild](https://github.com/fgimian/macbuild) project which I have used an MIT license on.

I just wanted to ask what license this module is released under, am I free to do what I like with it? :smile: 

Thanks heaps
Fotis

**Comment by mtneug** [comment]
Hi @fgimian, glad this is helping you.

I updated the project with a [license file](https://github.com/mtneug/ansible-modules-plist/blob/master/LICENSE.md) containing the MIT license. Note that I [copied](https://github.com/mtneug/ansible-modules-plist/blob/0f98f83d6f917360345154195143dcd4fe2441c4/library/plist_file.py#L85) one snippet from Stack Overflow. I gave credit for that but I'm not sure how this relates to copyright laws. At least in Germany copying such small snippets should not be a problem (not a lawyer).

This project also has a readme now.

**Comment by fgimian** [comment]
Hey @mtneug, thank you so much :smile: 

You're welcome to check out my version [here](https://github.com/fgimian/macbuild/blob/master/library/plist.py) and take anything you like :smile: 

Some improvements I've made are:
- Minor touch-ups to code and variable names
- Addition of backup feature and file features
- Ability to specify NSGlobalDomain or "Apple Global Domain" to reach global preferences
- Support for App Store apps when specifying a domain

A little tip, be a little careful with Ansible 1.9.x when it comes to variables.  It seems that 1.9.x converts any variables that you pass into modules into a string except for lists and dicts.

e.g. assuming you had some vars predefined

``` yaml
- name: example 1
  plist_file:
    dest: /tmp/example.plist
    key: "{{ key }}"
    value: "{{ value }}"
```

If `value` is set to `yes` for example, you'll end up with `'True'` instead of a boolean `True`.

The good news is that Ansible 2.0 fixes this and it works correctly on the current master branch at GitHub.

The only feature I have left to add to the plist module is the `state`, so one may say `state=absent` to remove a key.

All the best
Fotis

**Comment by mtneug** [comment]
Nice additions and thanks for the tip! I will apply the changes later this week or do you mind making a pull request?

I usually don't use `key`. Instead I use a `dictionary` as value to set a bunch of keys at once. The `booleans` work in this case.

By the way, you can install Ansible from `master` with Homebrew: `brew install ansible --HEAD`

**Comment by fgimian** [comment]
Oh wow, great advice, thank you!  Sure, I'd be happy to send you a pull request.  Will do soon :smile:

**Comment by fgimian** [comment]
Sadly, it seems that you MUST use the key even in Ansible 2.x because integers and floats don't get translated correctly (they become strings).  Your approach works very well.

Here's the playbook:

``` yaml
- name: set operating system and application defaults
  plist:
    dest: "{{ item.domain }}"
    value: "{{ item.defaults }}"
  with_items: "{{ osapp_defaults }}"
```

And then, for example, I do this in my vars:

``` yaml
# Set various defaults which will updat the relevant plist files
osapp_defaults:
  # System Preferences & Globals
  - domain: Apple Global Domain
    defaults:
      # General / Appearance / Use dark menu bar and Dock
      AppleInterfaceStyle: Dark
      # Keyboard / Keyboard / Key Repeat
      KeyRepeat: 2
      # Keyboard / Keyboard / Delay Until Repeat
      InitialKeyRepeat: 25
      # Keyboard / Keyboard / Use all F1, F2, etc. keys as standard function keys
      com.apple.keyboard.fnState: true
      # Keyboard / Text / Correct spelling automatically
      NSAutomaticSpellingCorrectionEnabled: false
      # Keyboard / Text / Use smart quotes and dashes
      NSAutomaticQuoteSubstitutionEnabled: false
      NSAutomaticDashSubstitutionEnabled: false
      # Keyboard / Shortcuts / Full Keyboard Access / All controls
      AppleKeyboardUIMode: 3
      # Mouse / Point & Click / Tracking
      com.apple.mouse.scaling: 1.0
...
```

I'll prepare a pull request soon with my changes :smile: 
Fotis
