### ISSUE TITLE
'str' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by cawilliamson** [mtneug/ansible-modules-plist#2]
Hey there!

This is possibly just me using the module wrong here but I am having the following error when I try and use anything other than a single value:

`'str' object has no attribute 'iteritems'`

A chunk of code which produces this in Ansible is:

```
- name: sort finder icons by name
  plist_file:
    dest: com.apple.finder
    value:
      'StandardViewSettings':
        'IconViewSettings':
          'arrangeBy': 'Name'
```

Any ideas here? I'm thinking somehow the value input is being interpreted by the python script as a single string instead of ending up as a dict.

Thanks!
